package com.mygitgor.seller_service.infrastructure.persistence.entity;

import org.springframework.data.relational.core.mapping.Table;
import org.springframework.data.annotation.Id;
import org.springframework.data.relational.core.mapping.Column;
import java.time.LocalDateTime;
import java.util.UUID;

@Table("sellers")
public record SellerEntity(
        @Id UUID id,
        String email,
        @Column("seller_name") String sellerName,
        @Column("store_name") String storeName,
        @Column("display_name") String displayName,
        String mobile,
        @Column("phone_number") String phoneNumber,
        @Column("profile_image") String profileImage,
        @Column("cover_image") String coverImage,
        @Column("business_details") String businessDetailsJson,
        @Column("bank_details") String bankDetailsJson,
        @Column("pickup_address") String pickupAddressJson,
        @Column("return_address") String returnAddressJson,
        @Column("warehouse_addresses") String warehouseAddressesJson,
        @Column("gst_number") String gstNumber,
        @Column("pan_number") String panNumber,
        @Column("tin_number") String tinNumber,
        @Column("business_registration_number") String businessRegistrationNumber,
        @Column("tax_info_verified") boolean taxInfoVerified,
        @Column("tax_info_verified_at") LocalDateTime taxInfoVerifiedAt,
        @Column("email_verified") boolean emailVerified,
        @Column("verification_status") String verificationStatus,
        @Column("account_status") String accountStatus,
        @Column("verification_document") String verificationDocumentJson,
        @Column("rejection_reason") String rejectionReason,
        @Column("rejected_at") LocalDateTime rejectedAt,
        String role,
        @Column("commission_rate") Double commissionRate,
        @Column("minimum_commission_rate") Double minimumCommissionRate,
        @Column("maximum_commission_rate") Double maximumCommissionRate,
        @Column("cashback_rate") Double cashbackRate,
        @Column("auto_accept_orders") boolean autoAcceptOrders,
        @Column("auto_confirm_delivery") boolean autoConfirmDelivery,
        @Column("processing_time_days") Integer processingTimeDays,
        @Column("shipping_time_days") Integer shippingTimeDays,
        @Column("free_shipping_threshold") Double freeShippingThreshold,
        @Column("domestic_shipping_cost") Double domesticShippingCost,
        @Column("international_shipping_cost") Double internationalShippingCost,
        @Column("store_logo") String storeLogo,
        @Column("store_banner") String storeBanner,
        @Column("store_description") String storeDescription,
        @Column("store_tagline") String storeTagline,
        @Column("store_website") String storeWebsite,
        @Column("store_email") String storeEmail,
        @Column("store_phone") String storePhone,
        @Column("social_media_links") String socialMediaLinks,
        @Column("store_category") String storeCategory,
        @Column("store_categories") String storeCategoriesJson,
        @Column("average_rating") Double averageRating,
        @Column("total_reviews") Integer totalReviews,
        @Column("total_positive_reviews") Integer totalPositiveReviews,
        @Column("total_neutral_reviews") Integer totalNeutralReviews,
        @Column("total_negative_reviews") Integer totalNegativeReviews,
        @Column("response_rate") Double responseRate,
        @Column("response_time_hours") Double responseTimeHours,
        @Column("followers_count") Integer followersCount,
        @Column("total_orders") Integer totalOrders,
        @Column("total_products") Integer totalProducts,
        @Column("total_active_products") Integer totalActiveProducts,
        @Column("total_out_of_stock_products") Integer totalOutOfStockProducts,
        @Column("total_earnings") Double totalEarnings,
        @Column("total_sales") Double totalSales,
        @Column("total_refunds") Double totalRefunds,
        @Column("total_tax") Double totalTax,
        @Column("net_earnings") Double netEarnings,
        @Column("average_order_value") Double averageOrderValue,
        @Column("conversion_rate") Double conversionRate,
        @Column("return_rate") Double returnRate,
        @Column("cancellation_rate") Double cancellationRate,
        @Column("canceled_orders") Integer canceledOrders,
        @Column("total_transactions") Integer totalTransactions,
        @Column("total_commission_paid") Double totalCommissionPaid,
        @Column("created_at") LocalDateTime createdAt,
        @Column("updated_at") LocalDateTime updatedAt,
        @Column("last_login_at") LocalDateTime lastLoginAt,
        @Column("email_verified_at") LocalDateTime emailVerifiedAt,
        @Column("business_verified_at") LocalDateTime businessVerifiedAt,
        @Column("last_active_at") LocalDateTime lastActiveAt,
        @Column("commission_updated_at") LocalDateTime commissionUpdatedAt,
        @Column("suspended_at") LocalDateTime suspendedAt,
        @Column("banned_at") LocalDateTime bannedAt,
        @Column("reactivated_at") LocalDateTime reactivatedAt,
        @Column("business_hours") String businessHoursJson
) {}
